[project]
name = "nonebot-plugin-picstatus"
dynamic = ["version"]
description = "A NoneBot2 plugin generates a picture which shows the status of current device"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.3.1",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot-plugin-alconna>=0.48.0",
    "nonebot-plugin-userinfo>=0.2.4",
    "nonebot-plugin-htmlrender>=0.3.2",
    "cookit[pydantic]>=0.6.5",
    "psutil>=6.0.0",
    "py-cpuinfo>=9.0.0",
    "anyio>=4.4.0",
    "httpx>=0.27.0",
    "jinja2>=3.1.4",
    "yarl>=1.9.4",
]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus"

[tool.pdm]

[tool.pdm.version]
source = "file"
path = "nonebot_plugin_picstatus/__init__.py"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
